before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: h2tLOLgYOvr5apDVhemet8iJgTloVCqYa1V5zvi24g9PPDbWx4D7YLDgGW5zencYLLc8ZOt5m7UNEm0EoG2b9I5gr85+GxcbxHlbQsa+17m3ByfO4m24Eoy3kHpwJOmsD7nQXSeNhTapdtH1gEskJM8jznhsVBAOj3usKTsF3fVD0Nbs40oN7v5wJQZlPNUu7cyDzlSc9lge0Y6HHwBnVON7k1sQBdz7lRrQDRrUc7bWlznRNCygGSVPf/FQlx5XUc99NB/Oc8TRzSnbP8PoBaq5dEETaY8GVKNBeR6UCPvu8OQDXB9inpYg4OMBrkXIpPp16xP5e6/ISZpmtsTHeRS8UHMUbLypbdOlThVmKe0xOaawENbMp1SwObr1fsaVTEu+uCoprdMXQUKAcmY+1c4lvOJbBoGl0yHQvG+nFMrLbKhXz19DS5jdgFkuyZGIsAPrIkWIF+IZgHZ9i4p+AYnfqelveGez2RnYPXfrlgDpaTXCjOJZAiGgmutCFNiwIuxRG9Vozimql7xxF9OxryTWxPGK/klJtDODv0cfjM7Y/SQ8OUxg0gxAycXPrHlb/m1Tfs2svRASWWkanrmLi1OEwVcaFbaNOcUZNztfC+1gxUqskWqaHQFPvo/2sXT32Nm9swtwvmd7oqi3HBQgnlw5JKtm7TV9/VYChzFd8Iw= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
